# Test express
GET http://localhost:3000/ HTTP/1.1

###

# Get countries
GET http://localhost:3000/countries?letters=А,Б,О HTTP/1.1


###

# Create card
POST http://localhost:3000/cards HTTP/1.1
Content-Type: application/json

{
  "companionCount": 3,
  "children": false,
  "startDate": "2024-06-28",
  "endDate": "2024-07-20",
  "countryList": [
    {"name": "Уганда"}
  ],
  "hashTags": ["#tag1", "#tag2"],
  "transport": ["plane", "walk"]
}

###

# Get cards by UUId
GET http://localhost:3000/cards/53b74ec4-e35b-490b-984f-9f582d2ad810?continents=North_America,Asia HTTP/1.1

###
