# Test express
GET http://localhost:3000/ HTTP/1.1

###

# Get countries
GET http://localhost:3000/countries?letters=А,Б,О HTTP/1.1


###

# Create card
POST http://localhost:3000/cards HTTP/1.1
Content-Type: application/json

{
  "companionCount": 3,
  "children": false,
  "startDate": "2024-06-25",
  "endDate": "2024-07-20",
  "countryList": [
    {"name": "Россия"}
  ],
  "hashTags": ["#tag1", "#tag2"],
  "transport": ["plane", "walk"]
}

###

# Get cards by UUId
GET http://localhost:3000/cards/0d864f6f-79ba-4dd2-8673-7034f20f92f1 HTTP/1.1

###
